project_name: tog

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/tog
      main: ./cmd/tog
      ldflags:
        - -s -w -X github.com/escaletech/tog-cli/cmd/tog.Version={{.Version}} -X github.com/escaletech/tog-cli/cmd/tog.BuildDate={{time "2006-01-02"}}
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip

brews:
  - name: tog
    tap:
      owner: escaletech
      name: homebrew-tap
    folder: Formula
    description: Tog CLI
    homepage: https://github.com/escaletech/tog-cli
    test: |
      help_text = shell_output("#{bin}/tog --help")
      assert_includes help_text, "Usage:"

nfpms:
  - license: MIT
    maintainer: Escale
    homepage: https://github.com/escaletech/tog-cli
    bindir: /usr/local
    formats:
      - deb
      - rpm

scoop:
  bucket:
    owner: escaletech
    name: scoop-tog
  commit_author:
    name: rodrigo.dumont
    email: rodrigo.dumont@escale.com.br
  homepage: https://github.com/escaletech/tog-cli
  skip_upload: auto
  description: Tog CLI
  license: MIT

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
